import { createRouter, createWebHistory } from 'vue-router'
import type { RouteRecordRaw } from 'vue-router'

const routes: RouteRecordRaw[] = [
  {
    path: '/',
    name: 'Home',
    component: () => import('@/views/Home.vue'),
    meta: { requiresAuth: false },
  },
  // 短路径重定向到 /admin 下的对应页面
  { path: '/groups', redirect: '/admin/groups' },
  { path: '/users', redirect: '/admin/users' },
  { path: '/organization', redirect: '/admin/organization' },
  { path: '/roles', redirect: '/admin/roles' },
  { path: '/conversations', redirect: '/admin/conversations' },
  { path: '/channels', redirect: '/admin/channels' },
  { path: '/apps', redirect: '/admin/apps' },
  { path: '/mini-apps', redirect: '/admin/mini-apps' },
  { path: '/statistics', redirect: '/admin/statistics' },
  { path: '/messages', redirect: '/admin/messages' },
  { path: '/message-search', redirect: '/admin/message-search' },
  { path: '/notifications', redirect: '/admin/notifications' },
  { path: '/blacklist', redirect: '/admin/blacklist' },
  { path: '/sensitive-words', redirect: '/admin/sensitive-words' },
  { path: '/operation-logs', redirect: '/admin/operation-logs' },
  { path: '/system-config', redirect: '/admin/system-config' },
  { path: '/version-management', redirect: '/admin/version-management' },
  { path: '/file-storage', redirect: '/admin/file-storage' },
  { path: '/server-monitor', redirect: '/admin/server-monitor' },
  { path: '/ai-assistant', redirect: '/admin/ai-assistant' },
  { path: '/ai-ops', redirect: '/admin/ai-ops' },
  { path: '/ai-config', redirect: '/admin/ai-config' },
  { path: '/mcp-tools', redirect: '/admin/mcp-tools' },
  { path: '/knowledge-graph', redirect: '/admin/knowledge-graph' },
  { path: '/vector-data', redirect: '/admin/vector-data' },
  { path: '/approvals', redirect: '/admin/approvals' },
  { path: '/auth-config', redirect: '/admin/auth-config' },
  { path: '/org-sync', redirect: '/admin/org-sync' },
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/Login.vue'),
    meta: { requiresAuth: false },
  },
  {
    path: '/admin',
    component: () => import('@/layouts/AdminLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      {
        path: '',
        name: 'Dashboard',
        component: () => import('@/views/Dashboard/index.vue'),
        meta: { title: '仪表盘' },
      },
      {
        path: 'users',
        name: 'Users',
        component: () => import('@/views/UserManagement/index.vue'),
        meta: { title: '用户管理' },
      },
      {
        path: 'organization',
        name: 'Organization',
        component: () => import('@/views/Organization.vue'),
        meta: { title: '组织架构' },
      },
      {
        path: 'groups',
        name: 'Groups',
        component: () => import('@/views/GroupManagement/index.vue'),
        meta: { title: '群组管理' },
      },
      {
        path: 'conversations',
        name: 'Conversations',
        component: () => import('@/views/Conversations.vue'),
        meta: { title: '会话管理' },
      },
      {
        path: 'channels',
        name: 'Channels',
        component: () => import('@/views/Channels.vue'),
        meta: { title: '频道管理' },
      },
      {
        path: 'apps',
        name: 'Apps',
        component: () => import('@/views/Apps.vue'),
        meta: { title: '应用管理' },
      },
      {
        path: 'mini-apps',
        name: 'MiniApps',
        component: () => import('@/views/MiniApps.vue'),
        meta: { title: '小程序管理' },
      },
      {
        path: 'messages',
        name: 'Messages',
        component: () => import('@/views/SystemMessages.vue'),
        meta: { title: '系统消息' },
      },
      {
        path: 'message-search',
        name: 'MessageSearch',
        component: () => import('@/views/MessageSearch/index.vue'),
        meta: { title: '消息搜索' },
      },
      {
        path: 'file-storage',
        name: 'FileStorage',
        component: () => import('@/views/FileManagement/Storage.vue'),
        meta: { title: '文件存储管理' },
      },
      {
        path: 'server-monitor',
        name: 'ServerMonitor',
        component: () => import('@/views/SystemMonitor/Server.vue'),
        meta: { title: '服务器监控' },
      },
      {
        path: 'notifications',
        name: 'Notifications',
        component: () => import('@/views/Notifications.vue'),
        meta: { title: '通知管理' },
      },
      {
        path: 'blacklist',
        name: 'Blacklist',
        component: () => import('@/views/Blacklist.vue'),
        meta: { title: '黑名单管理' },
      },
      {
        path: 'statistics',
        name: 'Statistics',
        component: () => import('@/views/Statistics.vue'),
        meta: { title: '数据统计' },
      },
      {
        path: 'roles',
        name: 'Roles',
        component: () => import('@/views/RoleManagement/index.vue'),
        meta: { title: '角色权限' },
      },
      {
        path: 'ai-assistant',
        name: 'AIAssistant',
        component: () => import('@/views/AIAssistant.vue'),
        meta: { title: 'AI 助手' },
      },
      {
        path: 'ai-ops',
        name: 'AIOps',
        component: () => import('@/views/AIOps.vue'),
        meta: { title: 'AI 运维面板' },
      },
      {
        path: 'ai-config',
        name: 'AIConfig',
        component: () => import('@/views/AIConfig/Providers.vue'),
        meta: { title: 'AI 模型配置' },
      },
      {
        path: 'mcp-tools',
        name: 'MCPTools',
        component: () => import('@/views/MCPTools.vue'),
        meta: { title: 'MCP 工具管理' },
      },
      {
        path: 'knowledge-graph',
        name: 'KnowledgeGraph',
        component: () => import('@/views/KnowledgeGraph.vue'),
        meta: { title: '知识图谱' },
      },
      {
        path: 'vector-data',
        name: 'VectorData',
        component: () => import('@/views/VectorData.vue'),
        meta: { title: '向量数据' },
      },
      {
        path: 'approvals',
        name: 'Approvals',
        component: () => import('@/views/UnifiedApprovalPanel.vue'),
        meta: { title: '审批管理' },
      },
      {
        path: 'auth-config',
        name: 'AuthConfig',
        component: () => import('@/views/AuthConfig/index.vue'),
        meta: { title: '认证配置' },
      },
      {
        path: 'org-sync',
        name: 'OrgSync',
        component: () => import('@/views/OrgSync/index.vue'),
        meta: { title: '组织架构同步' },
      },
      {
        path: 'sensitive-words',
        name: 'SensitiveWords',
        component: () => import('@/views/SensitiveWords.vue'),
        meta: { title: '敏感词管理' },
      },
      {
        path: 'operation-logs',
        name: 'OperationLogs',
        component: () => import('@/views/OperationLogs.vue'),
        meta: { title: '操作日志' },
      },
      {
        path: 'system-config',
        name: 'SystemConfig',
        component: () => import('@/views/SystemConfig.vue'),
        meta: { title: '系统配置' },
      },
      {
        path: 'version-management',
        name: 'VersionManagement',
        component: () => import('@/views/VersionManagement.vue'),
        meta: { title: '版本管理' },
      },
    ],
  },
  {
    path: '/403',
    name: 'Forbidden',
    component: () => import('@/views/Forbidden.vue'),
    meta: { requiresAuth: false },
  },
]

const router = createRouter({
  history: createWebHistory(),
  routes,
})

export default router
