#!/bin/bash

echo "=========================================="
echo "  QIM LDAP 测试服务器"
echo "=========================================="
echo ""

cd "$(dirname "$0")"

echo "正在启动 OpenLDAP 服务器..."
docker compose up -d

echo ""
echo "等待 LDAP 服务器启动..."
sleep 5

echo ""
echo "=========================================="
echo "  LDAP 服务器信息"
echo "=========================================="
echo ""
echo "LDAP 地址: localhost:389"
echo "Base DN:   dc=qim,dc=local"
echo "Admin DN:  cn=admin,dc=qim,dc=local"
echo "Admin 密码: admin123"
echo ""
echo "=========================================="
echo "  测试用户"
echo "=========================================="
echo ""
echo "用户1: testuser1 / 123456"
echo "  DN: uid=testuser1,ou=users,dc=qim,dc=local"
echo ""
echo "用户2: testuser2 / 123456"
echo "  DN: uid=testuser2,ou=users,dc=qim,dc=local"
echo ""
echo "管理员: admin / admin123"
echo "  DN: uid=admin,ou=users,dc=qim,dc=local"
echo ""
echo "=========================================="
echo "  PHP LDAP Admin (可选)"
echo "=========================================="
echo ""
echo "访问地址: https://localhost:6443"
echo "登录DN: cn=admin,dc=qim,dc=local"
echo "密码: admin123"
echo ""
echo "=========================================="
echo ""
