/**
 * 经典表情（QQ/微信风格动图，源自 oim-e）
 *
 * 资产自托管在 public/emoji/classic/{id}.gif。
 * 消息中以文字标记 [名称] 表示，渲染时替换为 <img>。
 */

export interface ClassicEmoji {
  id: number
  name: string
}

export const CLASSIC_EMOJIS: ClassicEmoji[] = [
  { id: 0, name: '惊讶' },
  { id: 1, name: '撇嘴' },
  { id: 2, name: '色' },
  { id: 3, name: '发呆' },
  { id: 4, name: '得意' },
  { id: 5, name: '流泪' },
  { id: 6, name: '害羞' },
  { id: 7, name: '闭嘴' },
  { id: 8, name: '睡' },
  { id: 9, name: '大哭' },
  { id: 10, name: '尴尬' },
  { id: 11, name: '发怒' },
  { id: 12, name: '调皮' },
  { id: 13, name: '呲牙' },
  { id: 14, name: '微笑' },
  { id: 15, name: '难过' },
  { id: 16, name: '酷' },
  { id: 17, name: '非典' },
  { id: 18, name: '抓狂' },
  { id: 19, name: '吐' },
  { id: 20, name: '偷笑' },
  { id: 21, name: '可爱' },
  { id: 22, name: '白眼' },
  { id: 23, name: '傲慢' },
  { id: 24, name: '饥饿' },
  { id: 25, name: '困' },
  { id: 26, name: '惊恐' },
  { id: 27, name: '流汗' },
  { id: 28, name: '憨笑' },
  { id: 29, name: '大兵' },
  { id: 30, name: '奋斗' },
  { id: 31, name: '咒骂' },
  { id: 32, name: '疑问' },
  { id: 33, name: '嘘...' },
  { id: 34, name: '晕' },
  { id: 35, name: '折磨' },
  { id: 36, name: '衰' },
  { id: 37, name: '骷髅' },
  { id: 38, name: '敲打' },
  { id: 39, name: '再见' },
  { id: 46, name: '猪头' },
  { id: 49, name: '拥抱' },
  { id: 53, name: '蛋糕' },
  { id: 54, name: '闪电' },
  { id: 55, name: '炸弹' },
  { id: 56, name: '刀' },
  { id: 57, name: '足球' },
  { id: 59, name: '便便' },
  { id: 60, name: '咖啡' },
  { id: 61, name: '饭' },
  { id: 62, name: '药丸' },
  { id: 63, name: '玫瑰' },
  { id: 64, name: '凋谢' },
  { id: 65, name: '示爱' },
  { id: 66, name: '爱心' },
  { id: 67, name: '心碎' },
  { id: 69, name: '礼物' },
  { id: 74, name: '太阳' },
  { id: 75, name: '月亮' },
  { id: 76, name: '强' },
  { id: 77, name: '弱' },
  { id: 78, name: '握手' },
  { id: 79, name: '胜利' },
  { id: 89, name: '西瓜' },
  { id: 96, name: '冷汗' },
  { id: 97, name: '擦汗' },
  { id: 98, name: '抠鼻' },
  { id: 99, name: '鼓掌' },
  { id: 100, name: '糗大了' },
  { id: 101, name: '坏笑' },
  { id: 102, name: '左哼哼' },
  { id: 103, name: '右哼哼' },
  { id: 104, name: '哈欠' },
  { id: 105, name: '鄙视' },
  { id: 106, name: '委屈' },
  { id: 107, name: '快哭了' },
  { id: 108, name: '阴险' },
  { id: 109, name: '亲亲' },
  { id: 110, name: '吓' },
  { id: 111, name: '可怜' },
  { id: 112, name: '菜刀' },
  { id: 113, name: '啤酒' },
  { id: 114, name: '篮球' },
  { id: 115, name: '乒乓' },
  { id: 117, name: '瓢虫' },
  { id: 118, name: '抱拳' },
  { id: 119, name: '勾引' },
  { id: 120, name: '拳头' },
  { id: 121, name: '差劲' },
  { id: 122, name: '爱你' },
  { id: 123, name: 'NO' },
  { id: 124, name: 'OK' },
  { id: 135, name: '招财进宝' },
  { id: 136, name: '双喜' },
  { id: 137, name: '鞭炮' },
  { id: 138, name: '灯笼' },
  { id: 139, name: '发财' },
  { id: 140, name: 'K歌' },
  { id: 141, name: '购物' },
  { id: 142, name: '邮件' },
  { id: 143, name: '帅' },
  { id: 144, name: '喝彩' },
  { id: 145, name: '祈祷' },
  { id: 146, name: '爆筋' },
  { id: 147, name: '棒棒糖' },
  { id: 148, name: '喝奶' },
  { id: 149, name: '下面' },
  { id: 150, name: '香蕉' },
  { id: 151, name: '飞机' },
  { id: 152, name: '开车' },
  { id: 153, name: '高铁左车头' },
  { id: 154, name: '车厢' },
  { id: 155, name: '高铁右车头' },
  { id: 156, name: '多云' },
  { id: 157, name: '下雨' },
  { id: 158, name: '钞票' },
  { id: 159, name: '熊猫' },
  { id: 160, name: '灯泡' },
  { id: 161, name: '风车' },
  { id: 162, name: '闹钟' },
  { id: 163, name: '打伞' },
  { id: 164, name: '彩球' },
  { id: 165, name: '钻戒' },
  { id: 166, name: '沙发' },
  { id: 167, name: '纸巾' },
  { id: 168, name: '药' },
  { id: 169, name: '手枪' },
  { id: 170, name: '青蛙' },
  { id: 171, name: '茶' },
  { id: 172, name: '眨眼睛' },
  { id: 173, name: '泪奔' },
  { id: 174, name: '无奈' },
  { id: 175, name: '卖萌' },
  { id: 176, name: '小纠结' },
  { id: 177, name: '喷血' },
  { id: 178, name: '斜眼笑' },
  { id: 179, name: 'doge' },
  { id: 180, name: '惊喜' },
  { id: 181, name: '骚扰' },
  { id: 182, name: '笑哭' },
  { id: 183, name: '我最美' },
  { id: 184, name: '河蟹' },
  { id: 185, name: '羊驼' },
  { id: 186, name: '栗子' },
  { id: 187, name: '幽灵' },
  { id: 188, name: '蛋' },
  { id: 189, name: '马赛克' },
  { id: 190, name: '菊花' },
  { id: 191, name: '肥皂' },
  { id: 192, name: '红包' },
  { id: 200, name: '拜托' },
  { id: 201, name: '点赞' },
  { id: 202, name: '无聊' },
  { id: 203, name: '托脸' },
  { id: 204, name: '吃' },
  { id: 205, name: '送花' },
  { id: 206, name: '害怕' },
  { id: 207, name: '花痴' },
  { id: 208, name: '小样儿' },
  { id: 209, name: '脸红' },
  { id: 210, name: '飙泪' },
  { id: 211, name: '我不看' },
  { id: 212, name: '托腮' },
]

/** 名称 → id 映射（重复名称取先出现的） */
const NAME_TO_ID = new Map<string, number>()
for (const e of CLASSIC_EMOJIS) {
  if (!NAME_TO_ID.has(e.name)) NAME_TO_ID.set(e.name, e.id)
}

/** 经典表情图片 URL */
export function classicUrl(id: number): string {
  return `/emoji/classic/${id}.gif`
}

/** 插入到输入框的文字标记 */
export function classicMarker(name: string): string {
  return `[${name}]`
}
