// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CacheAvatar(arg1:string):Promise<string>;

export function CancelScreenshot():Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function CleanupAvatarCache(arg1:number):Promise<void>;

export function CloseWindow():Promise<void>;

export function CompleteScreenshot(arg1:string,arg2:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:Array<number>,arg3:string):Promise<main.FileDialogResult>;

export function DownloadUpdate():Promise<main.UpdateInfo>;

export function FlashTray(arg1:boolean):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetPlatform():Promise<string>;

export function GetScreenSources():Promise<Array<main.ScreenSource>>;

export function InstallUpdate(arg1:string):Promise<void>;

export function IsMaximized():Promise<boolean>;

export function MaximizeWindow():Promise<void>;

export function MinimizeWindow():Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;

export function OpenFileDialog(arg1:main.FileDialogOptions):Promise<main.FileDialogResult>;

export function SaveFileAs(arg1:string,arg2:Array<number>):Promise<main.FileDialogResult>;

export function SaveScreenshot(arg1:Array<number>,arg2:string):Promise<main.FileDialogResult>;

export function StartScreenshot():Promise<void>;
