// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CacheAvatar(arg1) {
  return window['go']['main']['App']['CacheAvatar'](arg1);
}

export function CancelScreenshot() {
  return window['go']['main']['App']['CancelScreenshot']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CleanupAvatarCache(arg1) {
  return window['go']['main']['App']['CleanupAvatarCache'](arg1);
}

export function CloseWindow() {
  return window['go']['main']['App']['CloseWindow']();
}

export function CompleteScreenshot(arg1, arg2) {
  return window['go']['main']['App']['CompleteScreenshot'](arg1, arg2);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function FlashTray(arg1) {
  return window['go']['main']['App']['FlashTray'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetScreenSources() {
  return window['go']['main']['App']['GetScreenSources']();
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function IsMaximized() {
  return window['go']['main']['App']['IsMaximized']();
}

export function MaximizeWindow() {
  return window['go']['main']['App']['MaximizeWindow']();
}

export function MinimizeWindow() {
  return window['go']['main']['App']['MinimizeWindow']();
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function SaveFileAs(arg1, arg2) {
  return window['go']['main']['App']['SaveFileAs'](arg1, arg2);
}

export function SaveScreenshot(arg1, arg2) {
  return window['go']['main']['App']['SaveScreenshot'](arg1, arg2);
}

export function StartScreenshot() {
  return window['go']['main']['App']['StartScreenshot']();
}
